"""
Standen-scraper voor FIBS (Federazione Italiana Baseball Softball) — Serie A
Gold Baseball.
Source: https://www.fibs.it/en/events/2026-serie-a-gold-baseball/standings

BELANGRIJK: fibs.it blokkeert verzoeken die niet van een "schoon" IP-adres
komen met een 403 — dit gebeurt op CDN/WAF-niveau (CloudFront), vóórdat het
verzoek de site zelf bereikt. Bevestigd doordat zowel een kale request als
een volwaardige headless-browser vanuit GitHub Actions dezelfde CloudFront
403-pagina kregen ("Request blocked... Generated by cloudfront"), terwijl
diezelfde pagina vanaf een gewoon IP-adres prima laadt. Dit is dus geen
kwestie van browser-fingerprinting of JavaScript, maar puur IP-reputatie —
geen enkele lokale aanpassing in dit script lost dat op.

Oplossing: de request loopt via een scraping-proxy (ScraperAPI) die met
schone/residentiële IP-adressen werkt. De pagina zelf is gewoon server-side
gerenderde HTML (bevestigd: de standen-tabellen zitten al in de kale HTML,
zonder dat er JavaScript hoeft te draaien), dus we hebben GEEN
JavaScript-rendering nodig — een simpele HTTP-fetch via de proxy volstaat,
en dat is ook goedkoper/sneller dan render=true (dat extra crediet kost).

Benodigd: een SCRAPERAPI_KEY environment variable / GitHub Actions secret.
Aanmaken op https://www.scraperapi.com (gratis tier beschikbaar, ruim
voldoende voor 1x per dag scrapen).
"""
import json
import os
import re
import time
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timezone

URL = "https://www.fibs.it/en/events/2026-serie-a-gold-baseball/standings"
SCRAPERAPI_ENDPOINT = "http://api.scraperapi.com/"


def clean_text(html_fragment):
    """Alle tags verwijderen en witruimte normaliseren."""
    tekst = re.sub(r'<[^>]+>', '', html_fragment)
    return re.sub(r'\s+', ' ', tekst).strip()


def fetch_html(url, pogingen=3):
    api_key = os.environ.get("SCRAPERAPI_KEY")
    if not api_key:
        raise RuntimeError(
            "SCRAPERAPI_KEY ontbreekt. Zet 'm als GitHub Actions secret "
            "(Settings > Secrets and variables > Actions) en geef 'm door "
            "aan deze stap via env: SCRAPERAPI_KEY: ${{ secrets.SCRAPERAPI_KEY }}."
        )
    proxy_url = (
        f"{SCRAPERAPI_ENDPOINT}?api_key={api_key}"
        f"&url={urllib.parse.quote(url, safe='')}"
    )
    laatste_fout = None
    for poging in range(1, pogingen + 1):
        try:
            with urllib.request.urlopen(proxy_url, timeout=90) as resp:
                return resp.read().decode("utf-8", errors="replace")
        except urllib.error.HTTPError as e:
            laatste_fout = e
            body = ""
            try:
                body = e.read(500).decode("utf-8", errors="replace")
            except Exception:
                pass
            print(f"Poging {poging}/{pogingen}: HTTP {e.code} {e.reason} via proxy. Body: {body!r}")
            if poging < pogingen:
                time.sleep(5 * poging)
                continue
            raise
        except urllib.error.URLError as e:
            laatste_fout = e
            print(f"Poging {poging}/{pogingen}: netwerkfout via proxy: {e.reason}")
            if poging < pogingen:
                time.sleep(5 * poging)
                continue
            raise
    if laatste_fout:
        raise laatste_fout
    raise RuntimeError("fetch_html: onbekende fout zonder resultaat")


def parse_team_cellen(logo_td_html, naam_td_html):
    """
    Team staat verspreid over 2 <td>'s:
      - logo_td: <a href="team-link"><img src="logo" title="volledige naam"></a>
      - naam_td: <a href="team-link"><p class="team-name">CODE<br><small>NAAM</small></p></a>
    """
    href_match = re.search(r'href="([^"]+)"', naam_td_html) or re.search(r'href="([^"]+)"', logo_td_html)
    logo_match = re.search(r'<img[^>]+src="([^"]+)"', logo_td_html)
    code_match = re.search(r'<p class="team-name">\s*([^<]+?)\s*<br', naam_td_html, re.DOTALL)
    naam_match = re.search(r'<small>(.*?)</small>', naam_td_html, re.DOTALL)
    return {
        "team_link": href_match.group(1) if href_match else '',
        "team_logo": logo_match.group(1) if logo_match else '',
        "team_code": clean_text(code_match.group(1)) if code_match else '',
        "team":      clean_text(naam_match.group(1)) if naam_match else clean_text(naam_td_html),
    }


def parse_standings(html):
    result = {}
    # Elke groep/fase staat in een eigen "box-container" div met een <h3>
    # (groepsnaam) direct gevolgd door de standen-<table>. We splitsen op de
    # openings-marker (net als bij de andere scrapers op <h3>) i.p.v. te
    # proberen de sluitende </div> exact te matchen — de box-container-div
    # zit namelijk genest in andere divs (col-md-6, row, tab-pane, ...), dus
    # de eerstvolgende </div> is niet per se de eigen sluit-tag. Omdat we
    # per box toch alleen naar de EERSTE <h3> en <table> zoeken, maakt het
    # niet uit dat de rest van de pagina achter elk stuk "meehangt".
    boxes = re.split(r'<div class="box-container">', html)[1:]
    print(f"Debug: {len(boxes)} box-container-blokken gevonden.")
    for box in boxes:
        h3_match = re.search(r'<h3[^>]*>(.*?)</h3>', box, re.DOTALL)
        table_match = re.search(r'<table\b[^>]*>(.*?)</table>', box, re.DOTALL)
        if not h3_match or not table_match:
            print("Debug: box overgeslagen, geen <h3> en/of <table> gevonden.")
            continue
        fase_naam = clean_text(h3_match.group(1))
        table_html = table_match.group(1)
        rows = re.findall(r'<tr[^>]*>(.*?)</tr>', table_html, re.DOTALL)
        fase_rijen = []
        for row in rows:
            # Header-rij bestaat uit <th>'s, geen <td>'s — die valt hier
            # vanzelf af doordat tds_raw dan leeg blijft.
            tds_raw = re.findall(r'<td[^>]*>(.*?)</td>', row, re.DOTALL)
            # #, logo, naam, W, L, T, PCT, GB
            if len(tds_raw) < 8:
                continue
            positie = clean_text(tds_raw[0]).rstrip('.')
            team_info = parse_team_cellen(tds_raw[1], tds_raw[2])
            if not team_info["team"]:
                continue
            rij = {
                "positie":    positie,
                "team":       team_info["team"],
                "team_code":  team_info["team_code"],
                "team_logo":  team_info["team_logo"],
                "team_link":  team_info["team_link"],
                "w":          clean_text(tds_raw[3]),
                "l":          clean_text(tds_raw[4]),
                "t":          clean_text(tds_raw[5]),
                "pct":        clean_text(tds_raw[6]),
                "gb":         clean_text(tds_raw[7]),
            }
            fase_rijen.append(rij)
        if fase_rijen:
            result[fase_naam] = fase_rijen
        print(f"Debug: fase '{fase_naam}' — {len(fase_rijen)} teams.")
    return result


def main():
    print(f"Ophalen van {URL} via scraping-proxy...")
    html = fetch_html(URL)
    print(f"Ontvangen: {len(html)} bytes")
    standen = parse_standings(html)
    print(f"Gevonden groepen/fases: {list(standen.keys())}")
    output = {
        "bijgewerkt": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "bron":       URL,
        "standen":    standen,
    }
    with open("standen_serie_a_gold.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print("✅ standen_serie_a_gold.json opgeslagen")


if __name__ == "__main__":
    main()
